[package]
name = "mdns-core"
version = "0.1.0"
edition = "2021"

[dependencies]
mdns-sd = "0.10"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
if-addrs = "0.7"
